In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

import pandas as pd
import numpy as np
# import matplotlib.pyplot as plt
# from sklearn import tree
from sklearn.model_selection import train_test_split
# from sklearn.tree import DecisionTreeRegressor


DATASET_PATH = "/content/drive/MyDrive/dataset/Housing.csv"

# Leer la tabla
table = pd.read_csv(DATASET_PATH)


# Obtener X y Y
column_y_name = "price"
column_x_name = ["area", "bedrooms", "bathrooms"]


X = table.loc[:, column_x_name].to_numpy()
Y = table.loc[:, column_y_name].to_numpy()

print(X)
print(Y)

X_train, X_test, y_train, y_test = train_test_split(X, Y, random_state = 0, train_size = 0.70)
print(y_train)

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).
[[7420    4    2]
 [8960    4    4]
 [9960    3    2]
 ...
 [3620    2    1]
 [2910    3    1]
 [3850    3    1]]
[13300000 12250000 12250000 12215000 11410000 10850000 10150000 10150000
  9870000  9800000  9800000  9681000  9310000  9240000  9240000  9100000
  9100000  8960000  8890000  8855000  8750000  8680000  8645000  8645000
  8575000  8540000  8463000  8400000  8400000  8400000  8400000  8400000
  8295000  8190000  8120000  8080940  8043000  7980000  7962500  7910000
  7875000  7840000  7700000  7700000  7560000  7560000  7525000  7490000
  7455000  7420000  7420000  7420000  7350000  7350000  7350000  7350000
  7343000  7245000  7210000  7210000  7140000  7070000  7070000  7035000
  7000000  6930000  6930000  6895000  6860000  6790000  6790000  6755000
  6720000  6685000  6650000  6650000  6650000  6650000  6650000  6650000
  6629000  6615000  66150

In [ ]:
#a_00=X_train
#b_00=np.ones((381,1))
X_train2=np.append(np.ones((381,1)),X_train, axis=1)
print(X_train2.shape)
W=np.ones((4,1))
y_train=np.array(y_train)
print(y_train.shape)

(381, 4)
(1, 381)


In [ ]:
l2_n=100
while l2_n>0.01:
  fw=np.matmul(X_train2,W)
  print(fw.shape)
  e=np.subtract(fw,y_train.T)
  print(e.shape)
  alfa=1
  gfuncion=np.matmul(X_train2.T,e)/X_train2.shape[0]
  print(W.shape)
  print(gfuncion.shape)
  W=np.subtract(W,alfa*gfuncion)
  print(W.shape)
  l2_n=np.linalg.norm(gfuncion,2)
  print(l2_n)



(381, 1)
(381, 1)
(4, 1)
(4, 1)
(4, 1)
26003867071.821644
(381, 1)
(381, 1)
(4, 1)
(4, 1)
(4, 1)
7.68462637555187e+17
(381, 1)
(381, 1)
(4, 1)
(4, 1)
(4, 1)
2.2709500269548637e+25
(381, 1)
(381, 1)
(4, 1)
(4, 1)
(4, 1)
6.711079723190745e+32
(381, 1)
(381, 1)
(4, 1)
(4, 1)
(4, 1)
1.9832488833501365e+40
(381, 1)
(381, 1)
(4, 1)
(4, 1)
(4, 1)
5.860869331827149e+47
(381, 1)
(381, 1)
(4, 1)
(4, 1)
(4, 1)
1.7319958989074415e+55
(381, 1)
(381, 1)
(4, 1)
(4, 1)
(4, 1)
5.118370030094146e+62
(381, 1)
(381, 1)
(4, 1)
(4, 1)
(4, 1)
1.5125735448618377e+70
(381, 1)
(381, 1)
(4, 1)
(4, 1)
(4, 1)
4.4699361616374256e+77
(381, 1)
(381, 1)
(4, 1)
(4, 1)
(4, 1)
1.3209492759533202e+85
(381, 1)
(381, 1)
(4, 1)
(4, 1)
(4, 1)
3.903650805165881e+92
(381, 1)
(381, 1)
(4, 1)
(4, 1)
(4, 1)
1.1536014202872937e+100
(381, 1)
(381, 1)
(4, 1)
(4, 1)
(4, 1)
3.409106765204912e+107
(381, 1)
(381, 1)
(4, 1)
(4, 1)
(4, 1)
1.007454458028627e+115
(381, 1)
(381, 1)
(4, 1)
(4, 1)
(4, 1)
2.977215308599313e+122
(381, 1)
(381, 1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in matmul
  
